name: Hourly Update

on:
  push:
    branches:
      - master
  schedule:
    # Hourly
    - cron: "0 * * * *"

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.5.0
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3.5.1
        with:
          node-version: 16.x
      - run: npm install
      - run: node index.js
        env:
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
          AIRTABLE_BASE_ID: ${{ secrets.AIRTABLE_BASE_ID }}
          AIRTABLE_TABLE_ID: ${{ secrets.AIRTABLE_TABLE_ID }}
          GH_API_TOKEN: ${{ secrets.GH_API_TOKEN }}
